export type EnvironmentVariables = {
  DATABASE_URL: string;

  GATEWAY_SERVER_PORT: number;
  USERS_SERVER_PORT: number;

  CLIENT_URL: string;
  CLIENT_ACTIVATE_ACCOUNT_ROUT: string;
  CLIENT_RESET_PASSWORD_ROUT: string;

  CACHE_TTL: number;
  CACHE_TTL_FOR_FIND_ALL_: number;

  DEFAULT_PAGINATION_LIMIT: number;

  SMTP_HOST: string;
  SMTP_MAIL: string;
  SMTP_PASSWORD: string;
  SENDING_EMAIL_IDLE_PERIOD_IN_MS: number;

  JWT_SECRET: string;
  JWT_TOKEN_NAME: string;
  JWT_EXPIRES_IN: string;
  JWT_CODES_EXPIRES_IN: string;
  JWT_LINKS_EXPIRES_IN: string;

  COOKIE_ACTIVATION_TOKEN_EXPIRATION_TIME_IN_MS: number;
  COOKIE_JWT_TOKEN_EXPIRATION_TIME_IN_MS: number;
  COOKIE_ACTIVATION_TOKEN_NAME: string;
  COOKIE_IS_LOGGED_IN_NAME: string;
  COOKIE_FORGET_PASSWORD_TOKEN_NAME: string;
  COOKIE_FORGET_PASSWORD_TOKEN_EXPIRATION_TIME_IN_MS: number;
};
